/*
 * Copyright (c) 2009-2013 Topi Nieminen
 */
package fi.tnie.db.env;

import java.sql.SQLException;
import java.sql.Statement;

import fi.tnie.db.ent.Attribute;
import fi.tnie.db.ent.Entity;
import fi.tnie.db.ent.EntityException;
import fi.tnie.db.ent.EntityMetaData;
import fi.tnie.db.ent.Reference;
import fi.tnie.db.expr.InsertStatement;
import fi.tnie.db.types.ReferenceType;

public interface GeneratedKeyHandler {
	
	/**
	 * Process the values generated by the INSERT statement. 
	 * 
	 * @param <A>
	 * @param <R>
	 * @param <T>
	 * @param <E>
	 * @param <M>
	 * @param insert
	 * @param target
	 * @param qs
	 * @throws SQLException
	 * @throws EntityException
	 */	
	<
	    A extends Attribute,
	    R extends Reference,
	    T extends ReferenceType<A, R, T, E, ?, ?, M, ?>,
	    E extends Entity<A, R, T, E, ?, ?, M, ?>,
		M extends EntityMetaData<A, R, T, E, ?, ?, M, ?>
	>
	void processGeneratedKeys(InsertStatement insert, E target, Statement qs)
		throws SQLException, EntityException;
}
