@echo off


SET ROOT=%~dp0..
SET JARDIR=%ROOT%\lib
SET TEMPLATE_DIR=%ROOT%\war\WEB-INF\templates

REM Build java classpath:
SET META_GEN_CLASSPATH=%META_GEN_CLASSPATH%;%ROOT%\classes
SET META_GEN_CLASSPATH=%META_GEN_CLASSPATH%;%JARDIR%\util.jar
SET META_GEN_CLASSPATH=%META_GEN_CLASSPATH%;%JARDIR%\slf4j-api-1.7.5.jar
REM SET META_GEN_CLASSPATH=%META_GEN_CLASSPATH%;%JARDIR%\logback-core-1.0.13.jar
SET META_GEN_CLASSPATH=%META_GEN_CLASSPATH%;%JARDIR%\log4j-1.2.17.jar
SET META_GEN_CLASSPATH=%META_GEN_CLASSPATH%;%JARDIR%\slf4j-log4j12-1.7.5.jar


REM ready to go:
REM echo would run: 
@java -classpath %META_GEN_CLASSPATH% com.appspot.relaxe.build.Builder --help

@echo on